"use client";
import '../styles/globals.css'
// app/layout.js
import { Provider } from 'react-redux';
import store from '../store/store';
// export const metadata = {
//   title: 'Next.js',
//   description: 'Generated by Next.js',
// }

export default function RootLayout({ children }) {
  return (
    <Provider store={store}>
      <html lang="en">
        <body className='m-0 p-0'>
          {children}</body>
      </html>
    </Provider>
  )
}

